#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <math.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <pthread.h>

#include "../common/common.h"
#include "../common/cdf.h"
#include "../common/conn.h"

#ifndef max
    #define max(a,b) ((a) > (b) ? (a) : (b))
#endif
#ifndef min
    #define min(a,b) ((a) < (b) ? (a) : (b))
#endif

char config_file_name[80] = {'\0'}; //configuration file name
char dist_file_name[80] = {'\0'};   //size distribution file name
char fct_log_name[80] = "flows.txt";    //default log file name
int seed = 0; //random seed
unsigned int usleep_overhead_us = 0; //usleep overhead
struct timeval tv_start, tv_end; //start and end time of traffic
int num_new_conn = 0; //new established connections

/* per-server variables */
int num_server = 0; //total number of servers
int *server_port = NULL;   //ports of servers
char (*server_addr)[20] = NULL;    //IP addresses of servers
int *server_req_count = NULL;   //the number flows generated by each server

int num_service = 0; //Number of services
int *service_dscp = NULL;
int *service_prob = NULL;
int service_prob_total = 0;

int num_rate = 0; //Number of sending rates
int *rate_value = NULL;
int *rate_prob = NULL;
int rate_prob_total = 0;

double load = 0; //Network load (Mbps)
int req_total_num = 0; //Total number of requests
struct CDF_Table* req_size_dist;
int period_us;  //Average request arrival interval (us)

/* per-request variables */
int *req_size = NULL;   //flow size
int *req_server_id = NULL;  //server ID
int *req_dscp = NULL;   //DSCP of flow
int *req_rate = NULL;   //sending rate of flow
int *req_sleep_us = NULL; //sleep time interval
struct timeval *req_start_time; //start time of flow
struct timeval *req_stop_time;  //stop time of flow

struct Conn_List* connection_lists = NULL; //connection pool

/* Print usage of the program */
void print_usage(char *program);
/* Read command line arguments */
void read_args(int argc, char *argv[]);
/* Read configuration file */
void read_config(char *file_name);
/* Set request variables */
void set_req_variables();
/* Receive traffic from established connections */
void *listen_connection(void *ptr);
/* Generate flow requests */
void run_requests();
/* Generate a flow request to the server */
void run_request(unsigned int req_id);
/* Terminate all existing connections */
void exit_connections();
/* Terminate a connection */
void exit_connection(struct Conn_Node* node);
/* Print statistic data */
void print_statistic();
/* Clean up resources */
void cleanup();

int main(int argc, char *argv[])
{
    int i = 0;
    struct Conn_Node* ptr = NULL;

    /* read program arguments */
    read_args(argc, argv);

    /* set seed value for random number generation */
    if (seed == 0)
    {
        gettimeofday(&tv_start, NULL);
        srand((tv_start.tv_sec*1000000) + tv_start.tv_usec);
    }
    else
        srand(seed);

    /* read configuration file */
    read_config(config_file_name);
    /* set request variables */
    set_req_variables();

    /* Calculate usleep overhead */
    usleep_overhead_us = get_usleep_overhead(10);
    printf("===============================\n");
    printf("The usleep overhead is %u us.\n", usleep_overhead_us);
    printf("===============================\n");

    connection_lists = (struct Conn_List*)malloc(num_server * sizeof(struct Conn_List));
    if (!connection_lists)
    {
        cleanup();
        error("Error: malloc");
    }

    /* Initialize connection pool and establish connections to servers */
    for (i = 0; i < num_server; i++)
    {
        if (!Init_Conn_List(&connection_lists[i], i, server_addr[i], server_port[i]))
        {
            cleanup();
            error("Error: Init_Conn_List");
        }
        if (!Insert_Conn_List(&connection_lists[i], TG_PAIR_INIT_CONN))
        {
            cleanup();
            error("Error: Insert_Conn_List");
        }
        //Print_Conn_List(&connection_lists[i]);
    }

    /* Start threads to receive traffic */
    for (i = 0; i < num_server; i++)
    {
        ptr = connection_lists[i].head;
        while (true)
        {
            if (!ptr)
                break;
            else
            {
                pthread_create(&(ptr->thread), NULL, listen_connection, (void*)ptr);
                ptr = ptr->next;
            }
        }
    }

    printf("Start to generate requests\n");
    printf("===============================\n");
    gettimeofday(&tv_start, NULL);
    run_requests();

    /* Close existing connections */
    exit_connections();
    gettimeofday(&tv_end, NULL);
    printf("Terminate connections\n");
    printf("===============================\n");

    /* Wait for all threads to finish */
    for (i = 0; i < num_server; i++)
        Wait_Conn_List(&connection_lists[i]);

    print_statistic();

    /* Release resources */
    cleanup();
    return 0;
}

/* Print usage of the program */
void print_usage(char *program)
{
    printf("Usage: %s [options]\n", program);
    printf("-c <file>    name of configuration file (required)\n");
    printf("-l <file>    name of log file with flow completion times (default %s)\n", fct_log_name);
    printf("-s <seed>    random seed value (default current system time)\n");
    printf("-h           display help information\n");
}

/* Read command line arguments */
void read_args(int argc, char *argv[])
{
    int i = 1;

    if (argc == 1)
    {
        print_usage(argv[0]);
        exit(EXIT_SUCCESS);
    }

    while (i < argc)
    {
        if (strlen(argv[i]) == 2 && strcmp(argv[i], "-c") == 0)
        {
            if (i+1 < argc && strlen(argv[i+1]) < sizeof(config_file_name))
            {
                sprintf(config_file_name, "%s", argv[i+1]);
                i += 2;
            }
            /* cannot read IP address */
            else
            {
                printf("Cannot read configuration file name\n");
                print_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
        }
        else if (strlen(argv[i]) == 2 && strcmp(argv[i], "-l") == 0)
        {
            if (i+1 < argc && strlen(argv[i+1]) < sizeof(fct_log_name))
            {
                sprintf(fct_log_name, "%s", argv[i+1]);
                i += 2;
            }
            /* cannot read IP address */
            else
            {
                printf("Cannot read log file name\n");
                print_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
        }
        else if (strlen(argv[i]) == 2 && strcmp(argv[i], "-s") == 0)
        {
            if (i+1 < argc)
            {
                seed = atoi(argv[i+1]);
                i += 2;
            }
            /* cannot read port number */
            else
            {
                printf("Cannot read seed value\n");
                print_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
        }
        else if (strlen(argv[i]) == 2 && strcmp(argv[i], "-h") == 0)
        {
            print_usage(argv[0]);
            exit(EXIT_SUCCESS);
        }
        else
        {
            printf("Invalid option %s\n", argv[i]);
            print_usage(argv[0]);
            exit(EXIT_FAILURE);
        }
    }
}

/* Read configuration file */
void read_config(char *file_name)
{
    FILE *fd=NULL;
    char line[256]={'\0'};
    char key[80]={'\0'};
    num_server = 0;    //Number of senders
    int num_load = 0;   //Number of network loads
    int num_req = 0;    //Number of requests
    int num_dist = 0;   //Number of flow size distributions
    num_service = 0; //Number of services (optional)
    num_rate = 0; //Number of sending rates (optional)

    printf("Reading configuration file %s\n", file_name);

    /* Parse configuration file for the first time */
    fd = fopen(file_name, "r");
    if (!fd)
        error("Error: fopen");

    while (fgets(line, sizeof(line), fd) != NULL)
    {
        sscanf(line, "%s", key);
        if (!strcmp(key, "server"))
            num_server++;
        else if (!strcmp(key, "load"))
            num_load++;
        else if (!strcmp(key, "num_reqs"))
            num_req++;
        else if (!strcmp(key, "req_size_dist"))
            num_dist++;
        else if (!strcmp(key, "service"))
            num_service++;
        else if (!strcmp(key, "rate"))
            num_rate++;
        else
            error("Error: invalid key in configuration file");
    }

    fclose(fd);

    if (num_server < 1)
        error("Error: configuration file should provide at least one server");
    if (num_load != 1)
        error("Error: configuration file should provide one network load");
    if (num_req != 1)
        error("Error: configuration file should provide one total number of requests");
    if (num_dist != 1)
        error("Error: configuration file should provide one request size distribution");

    /* Initialize configuration */
    /* per-server variables*/
    server_port = (int*)malloc(num_server);
    server_addr = (char (*)[20])malloc(num_server * sizeof(char[20]));
    server_req_count = (int*)calloc(num_server, sizeof(int));  //initialize as 0
    /* service DSCP and probability */
    service_dscp = (int*)malloc(max(num_service, 1) * sizeof(int));
    service_prob = (int*)malloc(max(num_service, 1) * sizeof(int));
    /* sending rate value and probability */
    rate_value = (int*)malloc(max(num_rate, 1) * sizeof(int));
    rate_prob = (int*)malloc(max(num_rate, 1) * sizeof(int));

    if (!server_port || !server_addr || !server_req_count || !service_dscp || !service_prob || !rate_value || !rate_prob)
    {
        cleanup();
        error("Error: malloc");
    }

    /* Second time */
    num_server = 0;
    num_service = 0;
    num_rate = 0;

    fd = fopen(file_name, "r");
    if (!fd)
    {
        cleanup();
        error("Error: fopen");
    }

    while (fgets(line, sizeof(line), fd) != NULL)
    {
        remove_newline(line);
        sscanf(line, "%s", key);

        if (!strcmp(key, "server"))
        {
            sscanf(line, "%s %s %d", key, server_addr[num_server], &server_port[num_server]);
            printf("Server[%d]: %s, Port: %d\n", num_server, server_addr[num_server], server_port[num_server]);
            num_server++;
        }
        else if (!strcmp(key, "load"))
        {
            sscanf(line, "%s %lfMbps", key, &load);
            printf("Network Load: %.2f Mbps\n", load);
        }
        else if (!strcmp(key, "num_reqs"))
        {
            sscanf(line, "%s %d", key, &req_total_num);
            printf("Number of Requests: %d\n", req_total_num);
        }
        else if (!strcmp(key, "req_size_dist"))
        {
            sscanf(line, "%s %s", key, dist_file_name);
            printf("Loading request size distribution: %s\n", dist_file_name);

            req_size_dist = (struct CDF_Table*)malloc(sizeof(struct CDF_Table));
            if (!req_size_dist)
            {
                cleanup();
                error("Error: malloc");
            }

            init_CDF(req_size_dist);
            load_CDF(req_size_dist, dist_file_name);
            //print_CDF(req_size_dist);
            printf("Average request size: %.2f bytes\n", avg_CDF(req_size_dist));
        }
        else if (!strcmp(key, "service"))
        {
            sscanf(line, "%s %d %d", key, &service_dscp[num_service], &service_prob[num_service]);
            if (service_dscp[num_service] < 0 || service_dscp[num_service] >= 64)
            {
                cleanup();
                error("Illegal DSCP value");
            }
            else if (service_prob[num_service] < 0)
            {
                cleanup();
                error("Illegal DSCP probability value");
            }
            service_prob_total += service_prob[num_service];
            printf("Service DSCP: %d, Prob: %d\n", service_dscp[num_service], service_prob[num_service]);
            num_service++;
        }
        else if (!strcmp(key, "rate"))
        {
            sscanf(line, "%s %dMbps %d", key, &rate_value[num_rate], &rate_prob[num_rate]);
            if (rate_value[num_rate] < 0)
            {
                cleanup();
                error("Illegal sending rate value");
            }
            else if (rate_prob[num_rate] < 0)
            {
                cleanup();
                error("Illegal sending rate probability value");
            }
            rate_prob_total += rate_prob[num_rate];
            printf("Rate: %dMbps, Prob: %d\n", rate_value[num_rate], rate_prob[num_rate]);
            num_rate++;
        }
    }

    fclose(fd);

    /* By default, DSCP value is 0 */
    if (num_service == 0)
    {
        num_service = 1;
        service_dscp[0] = 0;
        service_prob[0] = 100;
        service_prob_total = service_prob[0];
        printf("Service DSCP: %d, Prob: %d\n", service_dscp[0], service_prob[0]);
    }

    /* By default, no rate limiting */
    if (num_rate == 0)
    {
        num_rate = 1;
        rate_value[0] = 0;
        rate_prob[0] = 100;
        rate_prob_total = rate_prob[0];
        printf("Rate: %dMbps, Prob: %d\n", rate_value[0], rate_prob[0]);
    }

    if (load > 0)
    {
        period_us = avg_CDF(req_size_dist) * 8 / load;
        if (period_us <= 0)
        {
            cleanup();
            error("Error: period_us is not positive");
        }
        printf("Average request arrival interval: %d us\n", period_us);
    }
    else
    {
        cleanup();
        error("Error: load is not positive");
    }
}

/* Set request variables */
void set_req_variables()
{
    int i = 0;
    unsigned long req_size_total = 0;
    unsigned long req_interval_total = 0;
    unsigned long rate_total = 0;
    double dscp_total = 0;

    /*request variables */
    req_size = (int*)malloc(req_total_num * sizeof(int));
    req_server_id = (int*)malloc(req_total_num * sizeof(int));
    req_dscp = (int*)malloc(req_total_num * sizeof(int));
    req_rate = (int*)malloc(req_total_num * sizeof(int));
    req_sleep_us = (int*)malloc(req_total_num * sizeof(int));
    req_start_time = (struct timeval*)calloc(req_total_num, sizeof(struct timeval));
    req_stop_time = (struct timeval*)calloc(req_total_num, sizeof(struct timeval));

    if (!req_size || !req_server_id || !req_dscp || !req_rate || !req_sleep_us || !req_start_time || !req_stop_time)
    {
        cleanup();
        error("Error: malloc per-request variables");
    }

    for (i = 0; i < req_total_num; i++)
    {
        req_size[i] = gen_random_CDF(req_size_dist);    //flow size
        req_server_id[i] = rand() % num_server; //server ID
        server_req_count[req_server_id[i]]++;   //per-server request number
        req_dscp[i] = gen_value_weight(service_dscp, service_prob, num_service, service_prob_total);    //flow DSCP
        req_rate[i] = gen_value_weight(rate_value, rate_prob, num_rate, rate_prob_total);   //flow sending rate
        req_sleep_us[i] = poission_gen_interval(1.0/period_us); //sleep interval based on poission process

        req_size_total += req_size[i];
        req_interval_total += req_sleep_us[i];
        dscp_total += req_dscp[i];
        rate_total += req_rate[i];
    }

    printf("===============================\n");
    printf("We generate %d requests.\n", req_total_num);

    for (i = 0; i < num_server; i++)
        printf("%s:%d    %d requests\n", server_addr[i], server_port[i], server_req_count[i]);

    printf("===============================\n");
    printf("The average arrival interval is %lu us.\n", req_interval_total/req_total_num);
    printf("The average request size is %lu bytes.\n", req_size_total/req_total_num);
    printf("The average DSCP value is %.2f\n", dscp_total/req_total_num);
    printf("The average flow sending rate is %lu mbps.\n", rate_total/req_total_num);
}

/* Receive traffic from established connections */
void *listen_connection(void *ptr)
{
    struct Conn_Node* node = (struct Conn_Node*)ptr;
    unsigned int meta_data_size = 4 * sizeof(unsigned int);
    unsigned int flow_id, flow_size, flow_tos, flow_rate;   //flow request meta data
    char read_buf[TG_MAX_READ] = {'\0'};

    while (true)
    {
        if (read_exact(node->sockfd, read_buf, meta_data_size, meta_data_size, false) != meta_data_size)
        {
            perror("Error: read meata data");
            break;
        }

        /* extract meta data */
        memcpy(&flow_id, read_buf, sizeof(unsigned int));
        memcpy(&flow_size, read_buf + sizeof(unsigned int), sizeof(unsigned int));
        memcpy(&flow_tos, read_buf + 2 * sizeof(unsigned int), sizeof(unsigned int));
        memcpy(&flow_rate, read_buf + 3 * sizeof(unsigned int), sizeof(unsigned int));

        if (read_exact(node->sockfd, read_buf, flow_size, TG_MAX_READ, true) != flow_size)
        {
            perror("Error: receive flow");
            break;
        }

        node->busy = false;
        pthread_mutex_lock(&(node->list->lock));
        if (flow_id != 0) //Not the special flow ID
        {
            node->list->flow_finished++;
            node->list->available_len++;
        }
        /* Ohterwise, it's a special flow ID to terminate connection.
           So this connection will no longer be available. */
        pthread_mutex_unlock(&(node->list->lock));

        /* A special flow ID to terminate persistent connection */
        if (flow_id == 0)
            break;
        else
            gettimeofday(&req_stop_time[flow_id - 1], NULL);
    }

    close(node->sockfd);
    node->connected = false;
    node->busy = false;

    return (void*)0;
}

/* Generate flow requests */
void run_requests()
{
    int i = 0;
    int sleep_us = 0;

    for (i = 0; i < req_total_num; i++)
    {
        sleep_us += req_sleep_us[i];
        if (sleep_us > usleep_overhead_us)
        {
            usleep(sleep_us - usleep_overhead_us);
            sleep_us = 0;
        }
        run_request(i);
    }
}

/* Generate a flow request to the server */
void run_request(unsigned int req_id)
{
    int server_id = req_server_id[req_id];
    int sockfd;
    unsigned int meta_data_size = 4 * sizeof(unsigned int);
    char buf[4 * sizeof(unsigned int)] = {'\0'}; // buffer to hold meta data
    unsigned int flow_id = req_id + 1; //We reserve flow ID 0 for special usage
    unsigned int flow_size = req_size[req_id];
    unsigned int flow_tos = req_dscp[req_id] * 4;   //ToS = DSCP * 4
    unsigned int flow_rate = req_rate[req_id];
    struct Conn_Node* node = Search_Conn_List(&connection_lists[server_id]);

    /* Cannot find available connection. Need to establish new connections. */
    if (!node)
    {
        if (Insert_Conn_List(&connection_lists[server_id], 1))
        {
            node = connection_lists[server_id].tail;
            printf("[%d] Establish a new connection to %s:%d (available/total = %u/%u)\n", ++num_new_conn, server_addr[server_id], server_port[server_id], node->list->available_len, node->list->len);
            pthread_create(&(node->thread), NULL, listen_connection, (void*)node);  //start thread on this new connection
        }
        else
        {
            printf("Cannot establish a new connection to %s:%d\n", server_addr[server_id], server_port[server_id]);
            return;
        }
    }

    /* fill in meta data */
    memcpy(buf, &flow_id, sizeof(unsigned int));
    memcpy(buf + sizeof(unsigned int), &flow_size, sizeof(unsigned int));
    memcpy(buf + 2 * sizeof(unsigned int), &flow_tos, sizeof(unsigned int));
    memcpy(buf + 3 * sizeof(unsigned int), &flow_rate, sizeof(unsigned int));

    /* Send request and record start time */
    gettimeofday(&req_start_time[req_id], NULL);
    sockfd = node->sockfd;
    node->busy = true;
    pthread_mutex_lock(&(node->list->lock));
    node->list->available_len--;
    pthread_mutex_unlock(&(node->list->lock));

    if(write_exact(sockfd, buf, meta_data_size, meta_data_size, 0, flow_tos, 0, false) != meta_data_size)
        perror("Error: write meta data");
}

/* Terminate all existing connections */
void exit_connections()
{
    int i = 0;
    struct Conn_Node* ptr = NULL;

    /* Start threads to receive traffic */
    for (i = 0; i < num_server; i++)
    {
        ptr = connection_lists[i].head;
        while (true)
        {
            if (!ptr)
                break;
            else
            {
                if (ptr->connected)
                    exit_connection(ptr);
                ptr = ptr->next;
            }
        }
    }
}

/* Terminate a connection */
void exit_connection(struct Conn_Node* node)
{
    int sockfd;
    unsigned int meta_data_size = 4 * sizeof(unsigned int);
    char buf[4 * sizeof(unsigned int)] = {'\0'}; // buffer to hold meta data
    unsigned int flow_id = 0; //A special flow ID to terminate connection
    unsigned int flow_size = 100;
    unsigned int flow_tos = 0;
    unsigned int flow_rate = 0;

    if (!node)
        return;

    memcpy(buf, &flow_id, sizeof(unsigned int));
    memcpy(buf + sizeof(unsigned int), &flow_size, sizeof(unsigned int));
    memcpy(buf + 2 * sizeof(unsigned int), &flow_tos, sizeof(unsigned int));
    memcpy(buf + 3 * sizeof(unsigned int), &flow_rate, sizeof(unsigned int));
    sockfd = node->sockfd;

    pthread_mutex_lock(&(node->list->lock));
    node->list->available_len--;
    pthread_mutex_unlock(&(node->list->lock));

    if(write_exact(sockfd, buf, meta_data_size, meta_data_size, 0, flow_tos, 0, false) != meta_data_size)
        perror("Error: write meta data");
}

void print_statistic()
{
    unsigned long duration_us = (tv_end.tv_sec - tv_start.tv_sec) * 1000000 + tv_end.tv_usec - tv_start.tv_usec;
    unsigned long req_size_total = 0;
    unsigned long fct_us;
    unsigned long goodput_mbps;
    int i = 0;
    FILE *fd = NULL;

    fd = fopen(fct_log_name, "w");
    if (!fd)
        error("Error: fopen");

    for (i = 0; i < req_total_num; i++)
    {
        req_size_total += req_size[i];
        fct_us = (req_stop_time[i].tv_sec - req_start_time[i].tv_sec) * 1000000 + req_stop_time[i].tv_usec - req_start_time[i].tv_usec;
        fprintf(fd, "%d %lu %d %d\n", req_size[i], fct_us, req_dscp[i], req_rate[i]);    //size, FCT(us), DSCP, rate(Mbps)

        if ((req_stop_time[i].tv_sec == 0) && (req_stop_time[i].tv_usec == 0))
            printf("Unfinished flow request %d\n", i);
    }

    fclose(fd);
    goodput_mbps = req_size_total * 8 / duration_us;
    printf("Achieved goodput is %lu mbps\n", goodput_mbps);
    printf("Write FCT results to %s\n", fct_log_name);
    printf("===============================\n");

    for (i = 0; i < num_server; i++)
        Print_Conn_List(&connection_lists[i]);
}

/* Clean up resources */
void cleanup()
{
    int i = 0;

    free(server_port);
    free(server_addr);
    free(server_req_count);

    free(service_dscp);
    free(service_prob);

    free(rate_value);
    free(rate_prob);

    free_CDF(req_size_dist);
    free(req_size_dist);

    free(req_size);
    free(req_server_id);
    free(req_dscp);
    free(req_rate);
    free(req_sleep_us);
    free(req_start_time);
    free(req_stop_time);

    if (!connection_lists)
    {
        for(i = 0; i < num_server; i++)
            Clear_Conn_List(&connection_lists[i]);
    }
    free(connection_lists);
}
